### ISSUE TITLE
Updating from within the game causes major problems

### ISSUE THREAD

**Issue by WellBeSerious** [PermaNulled/cartographer#105]
Updating from within the game (Cartographer > Update), the resolution became something really small (maybe 600 x something?) and I got stuck in the beginning place (Campaign and Network), not being able to move anywhere but see with mouse, and weapons working.

And now, even after deleting the game files and reinstalling, nothing changes!!!

**Comment by KILLER-CHIEF** [comment]
On a shortcut to halo2.exe add -windowed to the target path for windowed mode. then reset/fix the resolution from in the game. Try updating again. if it happens again please record it.

**Comment by WellBeSerious** [comment]
https://drive.google.com/open?id=1K3UwHxfD6scIrm40mlURmI0_JVFxR-jT
https://drive.google.com/open?id=1_dCVMjkRLphEAHzcNAXtkdJlkQ2PCAcp

Menu disappears, forcing me to Alt+Tab > close, then voices become overlapping. How do I reset the 'profile' at least?

**Comment by iSupersniper** [comment]
looks like your FOV is severely zoomed
try looking at your FOV settings real quick

**Comment by WellBeSerious** [comment]
As I said, the menu disappeared once in-game. That fixed the resolution, but I still can't move or see menu after. How do I reset what the update did?

**Comment by KILLER-CHIEF** [comment]
Reset your FoV settings when in the main menu then. if you need to start from all default cartographer settings then close the game then delete the file at `%LocalAppData%/Microsoft/Halo 2/halo2config1.ini` and open the game again

**Comment by WellBeSerious** [comment]
Doesn't do anything.

**Comment by KILLER-CHIEF** [comment]
So basically it could be some problem with the latest update that appears to only affect you. Try downloading this old version to your game's install directory and see if it really is due to the latest update: https://cartographer.online/h2update/0.4.0.1/xlive.dll

**Comment by WellBeSerious** [comment]
I deleted all "halo2", "halo 2" values from regedit, all AppData, all Game Saves, Program Files. Works now. Only explanation is Applying Patch 1, Patch 2 1.01, and Updating in-game.

**Comment by bigtweekx** [comment]
How did you initially install your game?

**Comment by WellBeSerious** [comment]
Applied Patch 1 accidentally before game? I think. Then Patch 2, installed game, Update. Everything works currently without patches.
