### ISSUE TITLE
access violation crash at offset 0x001ac0ca

### ISSUE THREAD

**Issue by shayaantx** [PermaNulled/cartographer#11]
I was working with a player named seraph and he had crashes (only ever had the game run once, hasn't run since)

He's going to reinstall everything and see if that helps, but I'm adding this issue for future investigation, cause its not clear yet why it happens.

He was getting two crashes:
1) a access violation at fault offset 0x001ac0ca. The function at this fault offset gets called right before the error in 2), once that error is thrown, the same function here is called again - resulting in a access violation. Even tho the game was able to write to the same memory right before 2) error is thrown.

Faulting application name: halo2.exe, version: 1.0.0.11122, time stamp: 0x46d3153c
Faulting module name: halo2.exe, version: 1.0.0.11122, time stamp: 0x46d3153c
Exception code: 0xc0000005
Fault offset: 0x001ac0ca
Faulting process id: 0x1fb8
Faulting application start time: 0x01d23a238e386627
Faulting application path: E:\Halo 2\halo2.exe
Faulting module path: E:\Halo 2\halo2.exe
Report Id: a38dd59a-1a10-4a34-9534-d4985b56d815
Faulting package full name: 
Faulting package-relative application ID: 

Fault bucket -1130033585, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: halo2.exe
P2: 1.0.0.11122
P3: 46d3153c
P4: halo2.exe
P5: 1.0.0.11122
P6: 46d3153c
P7: c0000005
P8: 001ac0ca
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER210E.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_halo2.exe_10d394f458325d53c1f2dcca446bdfc7c7c74_62ff30d6_2b2f2757

Analysis symbol: 
Rechecking for solution: 0
Report Id: a38dd59a-1a10-4a34-9534-d4985b56d815
Report Status: 1
Hashed bucket: 5957c87fcd9edf0fccf7948de14e6763

2) when I debug the assembly directly on his machine, I saw a actual c++ exception thrown with error code 406d1388, which seems to be related to corrupt dxd or vc redist installs (happened for a few games - just search exception code 406d1388)

**Comment by ShadowTeddy** [comment]
an interesting thing to note is that i somehow managed to get halo 2 running on same PC/Hardware by putting the game in 1280x720

I dont know why this worked.

I honestly think it could be due to a defunc. OS
