### ISSUE TITLE
Enhancement - Search bar for Livelist

### ISSUE THREAD

**Issue by ChiefII7** [PermaNulled/cartographer#122]
I have been hearing a lot of people complain about the Network lists sorting, and making it hard to get in a game. I think it would be useful to add a search bar into the server list so that people wont have to deal with the sorting a just get into the game by searching it up.

**Comment by bigtweekx** [comment]
Aren't you banned for hacking? You dont need to worry about searching a server list that you cannot access

**Comment by ChiefII7** [comment]
![i can play halo 2](https://user-images.githubusercontent.com/38872954/39500473-f5ec98d6-4d71-11e8-9568-8e2a4c5a6e87.PNG)
The Server thing is just a consideration.

**Comment by KILLER-CHIEF** [comment]
The only reason it's hard is the issue of servers frequently disappearing of which using LIVE list will fix it. Therefore this is already under consideration/development as seen even in past closed issues.
