### ISSUE TITLE
broken Spartan textures

### ISSUE THREAD

**Issue by ChiefII7** [PermaNulled/cartographer#123]
![wierd spartan textures](https://user-images.githubusercontent.com/38872954/39666242-d5bc8eb0-505d-11e8-8a1f-3f9442eb2099.PNG)
I went to change my spartan, and it appeared like this. Its also the same for the elite
![weird elite textures](https://user-images.githubusercontent.com/38872954/39666260-1b9bee62-505e-11e8-8b5a-3e6d9df6eeb2.PNG)

**Comment by num0005** [comment]
Could you try and explain your issue better?

**Comment by ChiefII7** [comment]
I was talking about how the armor looked "stained" But the devs in discord told me it was dynamic lighting

**Comment by KILLER-CHIEF** [comment]
I think he means the Level of Detail on that elite model. 'Is it usually that low in the menu?' would be his question.
