### ISSUE TITLE
Game will not launch without Admin privilege

### ISSUE THREAD

**Issue by hexthat** [PermaNulled/cartographer#137]
I was unable to load game without enabling admin privilege.

**Comment by KILLER-CHIEF** [comment]
On the current public release v0.4.0.4?

**Comment by pnill** [comment]
development branch

**Comment by iSupersniper** [comment]
Seems to be related to log write permissions in protected environment folder paths.

**Comment by pnill** [comment]
This is related to the log creation happening even when debug logs are turned off due to some changes made by Num, we'll have to review where we're storing logs and possibly store in AppData or Documents folders instead to avoid it.

**Comment by iSupersniper** [comment]
Temp solution in this commit: https://github.com/PermaNulled/cartographer/commit/f30a8f1cbe90d133fe2113c649d3e713bdef9465
