### ISSUE TITLE
Lan Support for Offline mode

### ISSUE THREAD

**Issue by Himanshu-01** [PermaNulled/cartographer#141]
A lot of people have been asking it lately including me :p

Need an implementation to support Lan instances for Offline Mode

Either way  Lan support with Multi instance on same computer can be very helpful for testing debugging purposes as well

**Comment by pnill** [comment]
If we ever get to a point the data is able to be handled offline once we switch lists, I'll look into doing this.

**Comment by nukeulater** [comment]
I implemented basic support for this, it has some limitations but gets the job done.
