### ISSUE TITLE
Game does not save refresh rate of monitor and has to be set upon each game launch

### ISSUE THREAD

**Issue by UncutFighter** [PermaNulled/cartographer#149]
The game will not save your preferred refresh rate (120hz, 144hz, etc.) when you select it from the video settings. It defaults to 60 each time the game reopens and has to be set again.

**Comment by Keith94** [comment]
Can confirm.

**Comment by Keith94** [comment]
In 0.5.2.0, I didn't notice a refresh rate option. How do I use it?

**Comment by General-101** [comment]
Not out yet

**Comment by CarlosACepeda** [comment]
Also the fullscreen option has the same behavior, it has to be set each time you start the game, can you confirm this behavior yourselves?

**Comment by iSupersniper** [comment]
@CarlosACepeda please verify you are not running the game with the -windowed startup parameter.

**Comment by CarlosACepeda** [comment]
How do I check for that parameter?, if I have the game pinned at the task bar, it's not a shortcut on the desktop

**Comment by iSupersniper** [comment]
Feature added in commit: https://github.com/PermaNulled/cartographer/commit/cfcff5ee8bcf59fed16c16e2fe050c6d0634e834
