### ISSUE TITLE
Dedicated server lag

### ISSUE THREAD

**Issue by NukeULater** [PermaNulled/cartographer#16]
Every dedicated server is lagging (no matter where they are located, US or EU).
For example, I live in EU, and every dedi EU server is lagging (players warping, 2 grenades at a time,people shooting more than 1 sniper bullet, tons of bluescreens)
The only thing that fixes this is a server restart.
Well, that is just a temporary fix.A server that was restarted will lag again after a day or even after a few matches.

I'm opening this issue because a cosnsiderable amount of players are encountering this issue and will make a lot of new players drop off.
Also ,this issue is new (4 months ago the game was just fine).

**Comment by LavenderMoon** [comment]
Sounds like a memory leak.

**Comment by bigtweekx** [comment]
So when is this going to be fixed, nuke? :)

**Comment by NukeULater** [comment]
@LavenderMoon yea, that might be true

**Comment by PermaNulled** [comment]
Can't find any evidence of this, going to close pending further research.

**Comment by NukeULater** [comment]
It seems like the issue has been fixed.
