### ISSUE TITLE
Some Issues preventing release of current code

### ISSUE THREAD

**Issue by General-101** [PermaNulled/cartographer#162]
Just wanted to make a list here so that we can start checking it twice so that we are aware of the issues that currently exist before an update can be done.

1. Map downloading in the live browser does not function well. When a custom map is played on live it will bring up the default menu that asks if the player would like to download this map from host. This can actually mess with the map downloader from time to time. Someone either needs to tie Yoshi's map downloading code to this menu or remove this menu from showing up at all.
EDIT:This issue has been taken cared of.

2. Map downloading doesn't work at all at time of writing. At some point during the live stuff map downloading just stopped working. Last time this seemed to be related to clients not getting the map name? Need someone to confirm this.
EDIT:This issue has been taken cared of.

3. Voice chat needs ingame menu options to disable or enable it along with other helpful things like push to talk and muting other players. This doesn't really prevent a release but it's kinda needed if we want a good experience with these things.

4. Extra settings doesn't work for clients at the moment. Ever since custom packets were disabled due to crashes on live this pretty much only works for host now. It needs to be disabled or finished.

There are other minor issues like things related to the state of GraveRobber and such but none of them should be "prevent release" worthy. These are the current issues I see with the dev preview dll.

**Comment by General-101** [comment]
Adding some things I just remembered.

5. Party management apparently causes a crash? This is the party management button found in the pregame lobby. The one ingame does not have this issue.

6. Game currently requires admin to start.

**Comment by bigtweekx** [comment]
7. My game crashes after sitting in the LIVE server browser for an extended period of time (20-30 minutes it seems like)

**Comment by General-101** [comment]
problem 7 Is probably solved by Nuke's latest commit. Need confirmation on this front.
