### ISSUE TITLE
Game still takes input even though console is open.

### ISSUE THREAD

**Issue by nukeulater** [PermaNulled/cartographer#166]
As the title says, the game still takes input even though console is open.

**Comment by pnill** [comment]
This is due to the fact it uses global keyboard hooks for console input, there was a way I had told Yoshi and Baked to fix this.

**Comment by shayaantx** [comment]
We stopped using global keyboard hooks, we use xliveinput  now. However
xliveinput doesn't respect preventing input from being passed to rest of
the game.

**Comment by shayaantx** [comment]
@PermaNulled you are referring to "fHandled" on the xlive_input_info struct, that doesn't work. We need to reverse the function calling it and see who is using it and why it doesn't work.

**Comment by nukeulater** [comment]
Added a dirty fix at the moment until a proper fix is found. 
https://github.com/PermaNulled/cartographer/commit/2a3209fdd140815fee5fdc8f05dd758e044f0cb2#diff-f463da3028d2874d1cd8cc0402a8c6cdR41

**Comment by nukeulater** [comment]
Fixed by https://github.com/NukeULater/cartographer/commit/8bf32075c021cd1e758c2467d03e16b614858c45 , it was the output param when XNotifyGetNext gets a XN_SYS_UI message
