### ISSUE TITLE
Issues found after release.

### ISSUE THREAD

**Issue by nukeulater** [PermaNulled/cartographer#185]
Here everyone can add issues found while playing Project Cartographer v0.5.0.0

1. Game details not showing up (QoS related issue).
![image](https://user-images.githubusercontent.com/18323679/50515169-cdcd9b00-0aab-11e9-8ebb-e0a745d0d8e8.png)
I think this only happens when more than 3 or 4 players are inside the lobby.

Edit: other people encounter this problem too

**Comment by nukeulater** [comment]
2. Leave lag? sometimes the game freezes for a split second when someone leaves.

Edit: i think this is caused by voice chat, i disabled it and didn't encounter it anymore.

**Comment by nukeulater** [comment]
3. Servers are laggy with around 12-16 players. (tested hosts that were fine before update)

**Comment by Himanshu-01** [comment]
4. Quickmatch Seems to fail consistently on the First try of every launch

**Comment by Himanshu-01** [comment]
5. Voice Icon doesnt pop up if users join mid game(Known but still)

**Comment by Himanshu-01** [comment]
> 1. Servers are laggy with around 12-16 players. (tested hosts that were fine before update)

It starts lagging for me as soon as i disable voice chat and play online
When i re enable it back ,it becomes normal
So Voice Chat -Disabled Causes Low FPS (Around  45-50)
Can someone confirm this as well?

**Comment by bigtweekx** [comment]
> So Voice Chat -Disabled Causes Low FPS (Around 45-50)
> Can someone confirm this as well?

I've never had frame drops to 15-30. My drops are 50-53. Idk the significance of that

**Comment by Himanshu-01** [comment]
> > So Voice Chat -Disabled Causes Low FPS (Around 45-50)
> > Can someone confirm this as well?
> 
> I've never had frame drops to 15-30. My drops are 50-53. Idk the significance of that

yea sry i meant 50 to 53
but its quite noticeable(jerky and slow gameplay) even though considering u get 60 straight with Voice enabled

**Comment by nukeulater** [comment]
6. You can still hear people in voice chat even though the game is minimized.

**Comment by Himanshu-01** [comment]
You running on Windows 10?

> 1. You can still hear people in voice chat even though the game is minimized.
