### ISSUE TITLE
Voice Chat

### ISSUE THREAD

**Issue by CarlosACepeda** [PermaNulled/cartographer#188]
Hi, I don't know if its a bug, but, my microphone appears to be active, I asked to my teammates if they can hear me, and they say no, also, I already configured my keyboard to voice chat with Left control key,
After all, i don't see my name being displayed on top of the score(when somebody talks) at this point Im pressing the button to talk
![halo 2 - project cartographer 29_12_2018 1_02_21 p m](https://user-images.githubusercontent.com/21343483/50540971-1481ca80-0b6a-11e9-9cfc-3fa16e252334.png)

**Comment by Himanshu-01** [comment]
For Voice chat
The Host/Server owner needs to port forward and enable it from his end too

**Comment by CarlosACepeda** [comment]
Everyone can talk, not me, haha :( I don't know anything about ports and such

**Comment by Himanshu-01** [comment]
Try using the default button "N" once

**Comment by CarlosACepeda** [comment]
A question, when I talk, should my name Appear on top of the score bars?

**Comment by CarlosACepeda** [comment]
![halo 2 - project cartographer 29_12_2018 1_13_13 p m](https://user-images.githubusercontent.com/21343483/50541111-7e02d880-0b6c-11e9-828f-a6924f2c3119.png)
Im 'Bash' I appear to be talking, or something, I dont know what a bright speaker means, lol.
But, Pressing N key does nothing.

**Comment by Himanshu-01** [comment]
If that is lighting that means your Voice is working as it should

**Comment by CarlosACepeda** [comment]
Its okay if it lights even when I'm not pressing 'n' key? at that moment I was not pressing any key

**Comment by Himanshu-01** [comment]
When it comes to Mainmenu Lobby,then YES

**Comment by CarlosACepeda** [comment]
Okay, thanks for all the clarification, very kind! Sorry for asking, so, if when I'm in the game playing, and I press the key to talk, should my name appear on the screen?

**Comment by CarlosACepeda** [comment]
Closing this because is invalid as voice chat is no longer in the mod in the current version 5.3.0
