### ISSUE TITLE
multiple instancing not working

### ISSUE THREAD

**Issue by h2noob** [PermaNulled/cartographer#191]
even with an xinput dll in the halo 2 folder, the second instance won't start because xinput is apparently missing

**Comment by General-101** [comment]
For whatever reason the xinput dll isn't being moved into the p0# folders in xinput. Moving it in manually should take care of that. I've had this same issue.

**Comment by h2noob** [comment]
duraz02.ini doesn't get created, nor is it used

**Comment by KILLER-CHIEF** [comment]
You can't just move xinput into the p0# folders and expect it to use the numbered INI files. Someone obviously broke my code that handles all of that. Spoiler alert it involves checksumming files.

**Comment by iSupersniper** [comment]
Issue resolved in commit: https://github.com/PermaNulled/cartographer/commit/b779a8577868dbd63114273333809d83c8d62b91
