### ISSUE TITLE
Build Time Status Blinking (Enhanced NVIDIA settings)

### ISSUE THREAD

**Issue by Catarax** [PermaNulled/cartographer#2]
When I enhance graphics of Halo 2 with the NVIDIA panel, the whole build message+connected will blink.
It will not blink if I use the default NVIDIA configuration.

**Global config =>**

![screenshot_1](https://cloud.githubusercontent.com/assets/3964507/18109469/b5b0cb1a-6f11-11e6-8d42-25781d2206ea.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/3964507/18109472/b5b874b4-6f11-11e6-95fc-7cf1da42e119.png)

**Halo 2 config =>**
![screenshot_3](https://cloud.githubusercontent.com/assets/3964507/18109470/b5b33be8-6f11-11e6-920e-c958e2ff3cff.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/3964507/18109471/b5b59dc0-6f11-11e6-8ff9-7ac7fb6d7e79.png)

I have no issue in-game, I don't know what is the parameter will lead to the bug, but I think you can easily reproduce it.

Windows 10 Anniversary - NVIDIA GTX 770 - Latest Drivers

**Comment by PermaNulled** [comment]
You can disable the build-text while you're in-game... personally I don't run windows anymore so I can't replicate/test this though I expect it has something to do with the way the hooks are done.
