### ISSUE TITLE
F8 not working properly

### ISSUE THREAD

**Issue by h2noob** [PermaNulled/cartographer#23]
As discussed in #dev_preview, pressing F8 does not always size to the actual window size. After main game loading screen, if one does not log in using a profile and arrive at main menu, pressing F8 has a tendency of not working. Even then, it may still show strange behavior.

**Comment by shayaantx** [comment]
@KILLER-CHIEF can you take a look

**Comment by pnill** [comment]
Tracking this issue in https://github.com/PermaNulled/cartographer/issues/120 instead.
