### ISSUE TITLE
[h2server] Servers become unjoinable for certain people after a long period of uptime

### ISSUE THREAD

**Issue by bigtweekx** [PermaNulled/cartographer#237]
Update 0.5.3.0 
"Official" Servers on LIVE list
Service mode

The issue is that random people seems to be unable to join the server, even though it has people in it and there are ample spots open in the lobby. Ex, CTF Coag 8/16. 

They can't join empty servers either, but once I restart the server, they are able to join it. 

This seems to happen if the server is popular and frequently populated. Or large number of player joins. Or uptime. The servers in question have been up for at least 1 week of continuous gameplay. 

On Network, these same servers would usually crash after extended uptime/player joins.

Perma mentioned something about a player cache in memory that never gets cleared

**Comment by pnill** [comment]
Has this been tested with https://github.com/PermaNulled/cartographer/pull/242 ?

**Comment by bigtweekx** [comment]
No. Not really any way to test that until that code makes it to a public release and I have a lot of uptime, player joins etc on the servers.

**Comment by iSupersniper** [comment]
Does this happen on both netcode lists? or just LIVE?

**Comment by bigtweekx** [comment]
I've seen this on both lists but much more rare on Network, however I think that Network servers crash rather than become unjoinable. I currently have servers on both lists and they seem to be behaving similarly

**Comment by pnill** [comment]
I've suspected for a long time that this is related to the fact the socket maps aren't cleared when an XNAddr is unregistered, which is why I referenced https://github.com/PermaNulled/cartographer/pull/242


@NukeULater what do you think?

**Comment by nukeulater** [comment]
@bigtweekx please upload the crash report.

**Comment by NukeULater** [comment]
This issue should be improved with [https://github.com/NukeULater/cartographer/commit/c696654656f04759ab05daf95d4d9d78872f4e0e](url) please check #test_dll.

**Comment by nukeulater** [comment]
This issue should be improved with https://github.com/NukeULater/cartographer/commit/c696654656f04759ab05daf95d4d9d78872f4e0e , please test DLL in #test_dll
