### ISSUE TITLE
[MetaLoader] Single Player Tags Injection

### ISSUE THREAD

**Issue by Himanshu-01** [PermaNulled/cartographer#239]
Pretty much broken due to how the code was initially hardcoded for MP shared map injection
This needs to be debugged and actually evaluate some hardcoded values during runtime.

Also I have currently no idea how much of interdependence SPShared has with the Campaign maps themselves.So this leaves for a confusion as to which map should be chosen for the StringID /tagRef comparisions when retargeting the meta for the map
In MP maps the cache meta tag modules are targeted for the MPShared itself.

**Comment by Berthalamew** [comment]
fixed as of:
https://github.com/pnill/cartographer/pull/670
