### ISSUE TITLE
Viewmodel customisation

### ISSUE THREAD

**Issue by xxmart1naxx** [PermaNulled/cartographer#243]
Since there are already values for the first person weapon position in the tags, it would be nice if it could be customisable from the Cartographer menu. Just a small feature request.

**Comment by iSupersniper** [comment]
This would also be helpful to maintain the proper fps model position when we adjust the field of view.

**Comment by nukeulater** [comment]
implemented in [pull 388](https://github.com/pnill/cartographer/pull/388)
