### ISSUE TITLE
No configuration files

### ISSUE THREAD

**Issue by TheRealSTG** [PermaNulled/cartographer#244]
I installed the cartographer mod from their site, everything worked out fine while downloading, but i seem to be missing the halo2config1.ini,etc files
i tried installing the game from other sources but i still have the same problem

**Comment by bigtweekx** [comment]
Check ``%localappdata%/Microsoft/Halo 2``
Do you see the ini files there?

**Comment by nukeulater** [comment]
They are created after you close the game (make sure your game closed gracefully/didn't crash)

**Comment by shayaantx** [comment]
No response in a month closing, can reopen if issue persists
