### ISSUE TITLE
Offline Mode "Create New Game"(LIVE) Causes Crash - Dec26 Release

### ISSUE THREAD

**Issue by AsKMoose** [PermaNulled/cartographer#248]
Attempting to create a new game in offline mode via the LIVE menu will cause the game to crash. I've attached the crash dump below. 
![issues_1](https://user-images.githubusercontent.com/34045130/71533846-13908f80-28c9-11ea-95b2-7dc52fe5f31e.PNG)
[halo2.exe_20191227-101344.zip](https://github.com/PermaNulled/cartographer/files/4006325/halo2.exe_20191227-101344.zip)

**Comment by nukeulater** [comment]
Added safety checks, please test DLL in #test_dll

**Comment by iSupersniper** [comment]
Issue fixed in latest update.
