### ISSUE TITLE
OGH2 mod applies in menus and in campaign - Dec26 release

### ISSUE THREAD

**Issue by AsKMoose** [PermaNulled/cartographer#250]
After leaving a game with the OGH2 mod enabled, the properties of the modded gametype are enabled in the menus and in campaign (i.e. 30 fps/30tick). Joining a multiplayer game without the OGH2 gametype reverts the game back to 60 fps. 
![issues_3](https://user-images.githubusercontent.com/34045130/71534052-1344c400-28ca-11ea-8630-8d15db3255b4.PNG)
![issues_4](https://user-images.githubusercontent.com/34045130/71534053-1344c400-28ca-11ea-8c55-04e0a37b9041.PNG)

**Comment by nukeulater** [comment]
Should be fixed, please check DLL in #test_dll

**Comment by General-101** [comment]
Fixed in 1f23907a8c780bd184d5b998bd918953bd22e0a8
