### ISSUE TITLE
[h2server] Servers do not exit gracefully

### ISSUE THREAD

**Issue by bigtweekx** [PermaNulled/cartographer#251]
Observed in 0.5.3.0 and 0.5.3.2. Servers (h2server.exe) do not behave nicely when you give the exit command in the cmd prompt or you stop the service. The process becomes unresponsive and needs to be killed from task manager. This does not happen all the time.
In my testing, this does not happen on 0.5.2.1 release.

**Comment by General-101** [comment]
Have also noticed this while messing with the dev preview testing servers on Super's dedi box

**Comment by nukeulater** [comment]
I have a fix, please check the dll in #test_dll

**Comment by iSupersniper** [comment]
Issue fixed in latest update.
