### ISSUE TITLE
read access violation during query server data

### ISSUE THREAD

**Issue by shayaantx** [PermaNulled/cartographer#255]
I noticed in debug mode (since its slow) when you exit the game while the live server list is built you get a crash, specifically in QueryServerData in ServerList.cpp.

It happens intermittently in debug mode. Looks like the json doc is either empty or being cleaned up when the process is exiting or the pvBuffer that gets passed in from XEnumerate is being cleaned up when the process is exiting and we aren't handling the edge case properly.

`		for (auto& property : doc["pProperties"].GetArray())
		{
			nResult->pProperties[current_property].dwPropertyId = property["dwPropertyId"].GetInt();
			nResult->pProperties[current_property].value.type = property["type"].GetInt();
`

![image](https://user-images.githubusercontent.com/5449086/71790418-5c99bf80-2ffe-11ea-9c0b-572b3e81de39.png)

![image](https://user-images.githubusercontent.com/5449086/71790437-80f59c00-2ffe-11ea-9250-4fb7f3f40b54.png)

**Comment by shayaantx** [comment]
Looking more at the doc object in the debugger it def has values in it, so its more likely the pvBuffer is being cleaned up somewhere while we are reading from it in this separate thread.

**Comment by shayaantx** [comment]
can fix this a few ways:
1) add a shutdown hook and kill all threads (although I don't know how the game handles this internally)
2) find the callee of xenumerate and find who owns the pvBuffer and cleans up and introduce a hook before cleanup to kill the server list thread

**Comment by nukeulater** [comment]
~~You need to implement XCancelOverlapped~~

**Comment by nukeulater** [comment]
Also it's slow because of https://github.com/PermaNulled/cartographer/blob/development/xlive/dllmain.cpp#L48

**Comment by nukeulater** [comment]
this should be fixed
