### ISSUE TITLE
Halo 2 has encountered a fatal error and needs to exit

### ISSUE THREAD

**Issue by CarlosACepeda** [PermaNulled/cartographer#278]
I can no longer open the game, it crashes:

![image](https://user-images.githubusercontent.com/21343483/91237073-41033680-e6ff-11ea-9130-1655a1382ad6.png)

[halo2.exe_20200825-181548.zip](https://github.com/pnill/cartographer/files/5126733/halo2.exe_20200825-181548.zip)

**Comment by nukeulater** [comment]
old error when we initially forced d3d9ex in a update, should be fixed
