### ISSUE TITLE
Instant Crash

### ISSUE THREAD

**Issue by anolddoomguy** [PermaNulled/cartographer#3]
When I first start the launcher, it just crashes

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	h2online (1).exe
  Problem Signature 02:	0.0.0.8
  Problem Signature 03:	57abe482
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.0.0.0
  Problem Signature 06:	4ba1da6f
  Problem Signature 07:	11cd
  Problem Signature 08:	89
  Problem Signature 09:	System.Windows.Markup.XamlParse
  OS Version:	6.1.7600.2.0.0.768.3
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by PermaNulled** [comment]
This issue belongs on the launcher git,
https://github.com/FishPhd/H2V-Online-Launcher
