### ISSUE TITLE
Add ability to download custom maps from a static repo

### ISSUE THREAD

**Issue by shayaantx** [PermaNulled/cartographer#30]
I already added this awhile back, but backed it out cause people wanted p2p. Now people want p2p and the ability to download from a map repo

**Comment by Aerocatia** [comment]
Having both is justified. A dedicated repo is good for speed as most people have bad upload however P2P is needed so you don't have to beg whoever is running it to add every map to said repo, kind of a problem currently in CE.

**Comment by pnill** [comment]
@shayaantx Isn't this done can we close this?

**Comment by shayaantx** [comment]
yea its done (its available in public release and dev branch)
