### ISSUE TITLE
Add voice chat

### ISSUE THREAD

**Issue by shayaantx** [PermaNulled/cartographer#31]
Voice chat was added originally but we had issues getting player information reliably, if we can get player info in a reliable fashion, voice chat can easily be added back.

Ask Rude_Yoshi for that code if you want it

**Comment by KILLER-CHIEF** [comment]
Current implementation (when running 2 clients and joined own game) freezes for a second or so whenever lobby options or each count of the start game countdown are made (every time there's a packet sent/received?).

**Comment by KILLER-CHIEF** [comment]
May not stem from voice chat. this still occurs with it turned off in the config file. I just never had this problem before until recently.

**Comment by shayaantx** [comment]
try in release mode

**Comment by KILLER-CHIEF** [comment]
Oh yeah that's fixed it. What's the cause? Heaps of logging I assume?

**Comment by shayaantx** [comment]
in debug mode, when free is called, free_dbg is called instead. free_dbg does more stuff than free, which results in some ugly performance in debug mode, specifically "the ability to keep freed blocks in the heap's linked list to simulate low memory conditions and a block type parameter to free specific allocation types." and "performs a validity check on all specified files and block locations before performing the free operation"

that's what I saw during profiling in debug mode and during release mode it doesn't happen

https://msdn.microsoft.com/en-us/library/16swbsbc.aspx

**Comment by pnill** [comment]
I plan to take a look at the current issues with this, for the most part it seems stable but has some issues in live that cause it to keep people connected to the wrong server after host-migration takes place.

There's also other issues like:

- Enabled 24/7 no option for push to talk
- Enemy teams can here each other.
- No distance volume relation.

**Comment by pnill** [comment]
This is now based on the XHV engine built-in game.
