### ISSUE TITLE
Add ability to launch games regardless if players can load the map or not

### ISSUE THREAD

**Issue by shayaantx** [PermaNulled/cartographer#34]
This isn't easy to do, I've achieved some form of this, but its still incomplete

Ask Rude_Yoshi for the code if you want to work on it

**Comment by iSupersniper** [comment]
Feature "completed" at this commit: https://github.com/PermaNulled/cartographer/commit/12d52da3fdf1e95ba3eeec2dbdd2ca1d545e8660
