### ISSUE TITLE
No zombie gets picked (sporadic)

### ISSUE THREAD

**Issue by bigtweekx** [PermaNulled/cartographer#35]
Games starts, no zombie gets chosen, game ends and goes back to the main menu. 1 fix is to have a client manually switch to green team. Sometimes if the host is green then everything works. Sometimes it just works. Could be a UDP issue

> 21/08/2017 19:37:20.885 [H2Mod-Infection] - PlayerInfected()
21/08/2017 19:37:20.888 [H2Mod-Infection] - PlayerInfected() PlayerInfected tweek compared to tweek
21/08/2017 19:37:20.890 [H2Mod-Infection] PlayerInfected() Made tweek infected!
21/08/2017 19:37:21.201 [h2mod-network] Player Connected!
21/08/2017 19:37:21.203 [h2mod-network] This player was already connected, sending them another packet letting them know they're authed already.
21/08/2017 19:37:21.714 [h2mod-network] Player Connected!
21/08/2017 19:37:21.718 [h2mod-network] This player was already connected, sending them another packet letting them know they're authed already.
21/08/2017 19:37:23.238 [h2mod-network] Player Connected!
21/08/2017 19:37:23.241 [h2mod-network] This player was already connected, sending them another packet letting them know they're authed already.
21/08/2017 19:37:23.944 [H2Mod-Infection] - Prespawn( 0 ) 
21/08/2017 19:37:23.946 [H2mod-Infection] - Prespawn(0) player tweek infection value is : 1
21/08/2017 19:37:23.948 [H2Mod-Infection] - Prespawn(0) playername tweek : tweek
21/08/2017 19:37:23.950 [H2Mod-Infection] - SpawnPlayer(0)
21/08/2017 19:37:24.759 [h2mod-network] Player Connected!
21/08/2017 19:37:24.761 [h2mod-network] This player was already connected, sending them another packet letting them know they're authed already.
21/08/2017 19:37:25.776 [h2mod-network] Player Connected!
21/08/2017 19:37:25.778 [h2mod-network] This player was already connected, sending them another packet letting them know they're authed already.
21/08/2017 19:37:26.711 [H2Mod-Infection] - PlayerInfected()
21/08/2017 19:37:27.801 [h2mod-network] Player Connected!
21/08/2017 19:37:27.804 [h2mod-network] This player was already connected, sending them another packet letting them know they're authed already.
21/08/2017 19:37:27.894 text_chat_packet=i
21/08/2017 19:37:27.896 text_chat_packet=i
21/08/2017 19:37:27.898 text_chat_packet=i
21/08/2017 19:37:27.900 text_chat_packet=i
21/08/2017 19:37:27.901 text_chat_packet=i
21/08/2017 19:37:27.903 text_chat_packet=i
21/08/2017 19:37:29.320 [h2mod-network] Player Connected!
21/08/2017 19:37:29.322 [h2mod-network] This player was already connected, sending them another packet letting them know they're authed already.
21/08/2017 19:37:29.848 [H2Mod-Infection] - Prespawn( 2 ) 
21/08/2017 19:37:29.851 [H2Mod-Infection] - SpawnPlayer(2)
21/08/2017 19:37:30.337 [h2mod-network] Player Connected!

**Comment by shayaantx** [comment]
This was with nukeulaters changes i believe

**Comment by iSupersniper** [comment]
It also occurs when the assigned zombie doesn't receive the UDP packet to switch teams.

**Comment by pnill** [comment]
This will be fixed when we start sending custom network data actively.
