### ISSUE TITLE
Hosting on the same network wouldn't let people to join their dedi

### ISSUE THREAD

**Issue by nukeulater** [PermaNulled/cartographer#36]
As the title says, people hosting on the same network woudn't allow people to join the dedi created on the network

**Comment by shayaantx** [comment]
some routers allow for this, some don't, needs more investigation

**Comment by jwshields** [comment]
I'm willing to do testing and help with this.

Normally I'd suggest this is a NAT hairpin issue, but I've never had issues with that on my router, running Shibby Tomato V140, I run multiple other services from behind my router, yet Project Cartographer doesn't want to work.

It might have to do with the hole punching, but I don't know C++ enough to even begin to debug or look at this.

**Comment by pnill** [comment]
This is related to individual networks and NAT Loopback, if people have issues with it they need to enable NAT loopback on their router.

Or they can use the built in WANIP, LANIP options to convert their WAN IP back to a LANIP when the system attempts to use it.
