### ISSUE TITLE
Option to enable or disable xDelay in pregame lobbies

### ISSUE THREAD

**Issue by iSupersniper** [PermaNulled/cartographer#38]
Incorporate the xDelay function properties in the DLL rather than relying on memory.

**Comment by KILLER-CHIEF** [comment]
xDelay should not force the delay to equal 0. does anyone realise how fucking gay that is? typing msgs in the ingame chat is literally kys. if someone's gonna do it, make it literally force a countdown so even if it gets delayed it's gonna keep counting from the same value. i'd do it but i've already got my hand up for heaps of things...

**Comment by KILLER-CHIEF** [comment]
xDelay is now done for halo2.exe.

**Comment by KILLER-CHIEF** [comment]
and now figured it out for h2server.exe too.
