### ISSUE TITLE
No Network - Launcher Removes itself

### ISSUE THREAD

**Issue by AnotherRandomTech** [PermaNulled/cartographer#40]
Launcher seems to remove itself if you have no internet connectivity, requires need to re-download/copy back the launcher to H2 folder.

Before:
![image](https://user-images.githubusercontent.com/31136246/30408927-825caac4-9934-11e7-8ebc-c562b7d50a5e.png)

After:
![image](https://user-images.githubusercontent.com/31136246/30408970-b52f125c-9934-11e7-8a31-5e82d4917720.png)

**Comment by shayaantx** [comment]
post this issue here, https://github.com/iSupersniper/H2Launcher
