### ISSUE TITLE
Launcher Crashing Upon Login and Settings being changed

### ISSUE THREAD

**Issue by Doldilic** [PermaNulled/cartographer#41]
I have all the required firmware, the launcher runs fine, until I decide to try to login or change my settings. Once the application tries to save the edits to the files, the app crashes.
[Error Log 2.txt](https://github.com/PermaNulled/cartographer/files/1326892/Error.Log.2.txt)
[Error log 1.txt](https://github.com/PermaNulled/cartographer/files/1326893/Error.log.1.txt)

**Comment by iSupersniper** [comment]
This is the wrong GitHub.  Please post this on the launcher GitHub.  Link is available in pinned messages on the discord
