### ISSUE TITLE
Cant see teammate emblems in non-zombie games

### ISSUE THREAD

**Issue by bigtweekx** [PermaNulled/cartographer#43]
Latest update added a feature that prevented humans in zombies (red team) from seeing teammate emblems. This is only supposed to activate in Zombies.

Seems that playing a Zombies game and then leaving to join a normal team game triggers this, but doesn't happen all the time.

Restarting the game restores normal team emblem behavior

**Comment by iSupersniper** [comment]
Fixed in merge request #44
