### ISSUE TITLE
[FeatureRequest] Handle map download with multiple instances.

### ISSUE THREAD

**Issue by BiatuAutMiahn** [PermaNulled/cartographer#458]
Using Nucleus CoOp, attempting to play with more than 1 instance. All players log in, and go to join game lobby.

Scenario 1:
Nobody has the map. Everyone is prompted to download the map. Map is downloaded then fails due to file being locked by another instance.

Scenario 2:
Nobody has map. Instance 1 downloads map. All other instances prompt for download as they do not check for maps except for on init.

Scenario 3:
Map exists in custom maps dir. All is good,

And a few proposed solutions:

1:
```
if (instanceNumber) {
    while (peer_count_with_map_status_downloading) {
        ReloadAllMaps();
        // wait 1000ms
    }
    // Return true for map being downloaded.
}
```

2:
if `instanceNumber==0`, and isMultiInstance: download map to `.part` file instead of `.map`, wait for `peer_count_with_map_status_downloading==0`.
with `instanceNumber>0` wait for `.part` to not exist. then return true for download complete.

3:
postfix `custom_maps_folder_path` with instance number before download if `isMultiInstance`, `instanceNumber>0`, and map does not exist in `custom_maps_folder_path`.

**Comment by Berthalamew** [comment]
Not relevant anymore as split screen is now supported and playing with multiple instances is mainly for dev/testing
