### ISSUE TITLE
Console doesn't display transparent backdrop ingame, only in menus/lobby

### ISSUE THREAD

**Issue by shayaantx** [PermaNulled/cartographer#50]
Not sure why it does this, assume its because I'm not saving the d3d render state properly, although if that was the case it wouldn't work in the menus.

Its not terrible bug (since the text and caret still display), but I would like it to be consistent everywhere

**Comment by shayaantx** [comment]
fixed by https://github.com/PermaNulled/cartographer/commit/2238a88462d9a66b9ff12800a91fbdcd9f526357

**Comment by shayaantx** [comment]
2238a88 didn't fix this completely it seems

**Comment by AsKMoose** [comment]
4 people different tested it, and it seems to work for them. I think its just u

**Comment by shayaantx** [comment]
ok i guess it works, just not for me consistently....
