### ISSUE TITLE
NetWorx "Ignore Lan traffic" option broke server list

### ISSUE THREAD

**Issue by Catarax** [PermaNulled/cartographer#63]
If you check this option in NetWorx to not analyse the LAN traffic, the server list of Halo 2 will not be generated at all.
Windows 10 Creators Update and Fall Update tested.

![1pvzagiotk_677-vve1ziq](https://user-images.githubusercontent.com/3964507/33282771-f84a7310-d3a9-11e7-8ee3-601ab6cba978.png)

NetWorx software : https://www.softperfect.com/products/networx/

**Comment by bigtweekx** [comment]
Close the launcher
Go to your halo 2 directory
Open xlive.ini
Make sure there is a login token. If not, you need to run the launcher and login
Change port = 1000 to something random like port = 34537
Save and close xlive.ini
Run halo2.exe
You should be able to see servers now

If not, then there is a firewall blocking your ports

**Comment by Catarax** [comment]
Updated details about the bug.

**Comment by num0005** [comment]
that makes sense since we are reusing code originally meant for LAN.

**Comment by pnill** [comment]
Actually, regardless of using code originally meant for LAN we're not broadcasting to LAN addresses 255.255.255.255, we broadcast direct to a master so it should not be seen as LAN traffic.

Though this seems to be an issue with your specific software. The only solution we're able to offer is don't use that software or check that option within that software.
