### ISSUE TITLE
Connecting to servers on the same network

### ISSUE THREAD

**Issue by ghost** [PermaNulled/cartographer#86]
It would be nice to have an option to somehow change ports.

With the game as is, players on the same local network can not join the same game, otherwise one of them gets booted out, and I suspect this is something to do with server session creation being unable to handle two players on the same network connection wise.

Something like this also happens with Warframe, but Warframe does indeed have the option for players to change the listening ports used, which fixes the problem.

Halo: Online also has this same exact issue, but no way to fix it.

As of right now, one of the players on a reliable VPN fixes the issue.

**Comment by bigtweekx** [comment]
xlive.ini there is a port setting. also you may not be able to join local networks even with different ports; this is a bug in our networking code

**Comment by ghost** [comment]
Alright. Thanks for the answer, hopefully it gets fixed.

**Comment by pnill** [comment]
To be clear this is not a bug in our networking code... this is an issue
with NAT loopback on most routers and the way they handle it, most games
simply have the ability to work around having to perform NAT loop back
where I personally have not found a good solution.

LAN and WAN IP configurations theoretically should account for this though.

**Comment by ghost** [comment]
Then I'm at a loss as to why Digital Extremes can easily accomplish a workaround for such an issue.

Good luck in your endeavors, I suppose this should be closed, since it won't be "fixed"?

**Comment by pnill** [comment]
Honestly I haven't been very productive lately so I'll try and do so some
research into what's going wrong and get back to you on this.

**Comment by ghost** [comment]
Hey man, no problem. I'll also do some research, then. If I find anything interesting, I'll report back here, assuming it's not closed or solved by then.

Until then, keep at the good work, sincerely. =D

**Comment by pnill** [comment]
If you're on the discord it would help to have you troubleshoot.

**Comment by ghost** [comment]
Yeah, I'll get on it when I can. I might even stick around to troubleshoot other stuff, I have a talent for finding issues to complain about. lol

**Comment by pnill** [comment]
Will provide updates to this issue overall on #97. This specific issue has been corrected for the user based on their own network configuration.
