### ISSUE TITLE
Console gets triggered by keys other than tilde (~)

### ISSUE THREAD

**Issue by bigtweekx** [PermaNulled/cartographer#88]
Apparently on keyboard that are not US layout, the console can get triggered by the key that is two spots to the left of L. 

On UK keyboards, this is the (@ ' ) key, and this causes issues in the in game login; people are unable to input the @ character during signup

![united_kingdom-keyboard](https://user-images.githubusercontent.com/18296142/34652771-55a46052-f3a8-11e7-947b-840f13f6e577.png)

**Comment by KILLER-CHIEF** [comment]
Changed hotkey to F10 to hopefully universally support more keyboards.
