### ISSUE TITLE
Escape key and lower Cancel button not working in Update Menu

### ISSUE THREAD

**Issue by TheRoboman** [PermaNulled/cartographer#96]
This is a minor issue, but neither the Escape keyboard command nor the lower onscreen Cancel button will exit the Update menu. Only the Cancel button listed as an option in the menu will exit the menu.

**Comment by KILLER-CHIEF** [comment]
A purposefully done feature due to other bugs in the halo 2 menu system. It's to prevent accidentally canceling downloads etc.
